server:
      port: 9000
graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: true
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL


datasource :
      db :
        username : root
        password : Dev@gianty123
        databaseUrl : jdbc:mysql://localhost:3306/gsop_hrm?useSSL=false&characterEncoding=UTF-8
        databaseDriver : com.mysql.jdbc.Driver

